services:
  mikrotik-dns:
    container_name: mikrotik-dns
    restart: unless-stopped
    build: .
    ports:
      - "5354:5354/udp"
    volumes:
      - ./data:/app/data
    networks:
      - internal
networks:
  internal:
    external: true
